### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mbprevot** [hersle/leaflet-route-print#3]
Is it possible to print two different route at the same time?
if so how?

Thank you

**Comment by hersle** [comment]
Not at this time, sorry!

With two routes, it would generally not be possible to find a sequence of rectangles that covers both routes.

**Comment by mbprevot** [comment]
for me the second route is always in the same rectangle as the first route, it is a variant

**Comment by hersle** [comment]
I see. It would certainly be possible to add this functionality, but I think it is outside the domain of this library, which only attempts to print the map along one route well.

Additional details in the map, such as roadside markers and alternative routes, should really be added by whichever larger client application that uses this library.

Anyway, it is not something I will add in the nearest future. Sorry!
